<template>
  <div class="breakdown-section">
    <div class="section-header">
      <span class="section-accent" style="background:#f59e0b"></span>
      <h2 class="section-title">Payroll Breakdown by Staff</h2>
    </div>

    <div class="breakdown-grid">
      <div v-for="row in rows" :key="row.userID" class="bc">
        <!-- Card top: avatar + name + payroll pill -->
        <div class="bc-top">
          <div class="bc-avatar" :style="{ background: avatarColor(row.fullName) }">
            {{ initials(row.fullName) }}
          </div>
          <div class="bc-info">
            <p class="bc-name">{{ row.fullName }}</p>
            <p class="bc-role">{{ row.role }}</p>
          </div>
          <span :class="['bc-pill', row.payrollCreated ? 'created' : 'pending']">
            {{ row.payrollCreated ? 'Created' : 'Pending' }}
          </span>
        </div>

        <!-- Shift stats row -->
        <div class="bc-stats">
          <div class="bc-stat">
            <p class="bsv">{{ row.shiftsAssigned }}</p>
            <p class="bsl">Shifts</p>
          </div>
          <div class="bc-stat">
            <p class="bsv green">{{ row.completed }}</p>
            <p class="bsl">Done</p>
          </div>
          <div class="bc-stat">
            <p class="bsv" :class="row.late > 0 ? 'amber' : ''">{{ row.late }}</p>
            <p class="bsl">Late</p>
          </div>
          <div class="bc-stat">
            <p class="bsv" :class="row.missed > 0 ? 'red' : ''">{{ row.missed }}</p>
            <p class="bsl">Missed</p>
          </div>
          <div class="bc-stat">
            <p class="bsv">{{ row.hoursWorked.toFixed(1) }}h</p>
            <p class="bsl">Hours</p>
          </div>
        </div>

        <!-- Pay breakdown -->
        <div class="bc-pay">
          <div class="pay-row">
            <span class="pay-lbl">Hourly Rate</span>
            <span class="pay-val mono">{{ fmtRM(row.hourlyRate) }}/h</span>
          </div>
          <div class="pay-row">
            <span class="pay-lbl">Pay per Shift <span class="pay-hint">(avg {{ row.avgHoursPerShift.toFixed(1) }}h/shift)</span></span>
            <span class="pay-val mono">{{ fmtRM(row.payPerShift) }}</span>
          </div>
          <div class="pay-divider"></div>
          <div class="pay-row total-row">
            <span class="pay-lbl total-lbl">Total Pay</span>
            <span class="pay-val total-val mono">{{ fmtRM(row.totalPay) }}</span>
          </div>
        </div>

        <!-- Receipt status -->
        <div :class="['bc-receipt', row.payrollReceived ? 'yes' : 'no']">
          <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5">
            <polyline v-if="row.payrollReceived" points="20 6 9 17 4 12"/>
            <circle   v-else cx="12" cy="12" r="10"/>
          </svg>
          {{ row.payrollReceived ? 'Payment Received' : 'Awaiting Receipt Confirmation' }}
        </div>
      </div>
    </div>

    <!-- Grand total banner -->
    <div class="grand-total">
      <span class="gt-label">Total Payroll for {{ periodLabel }}</span>
      <span class="gt-value">{{ fmtRM(grandTotal) }}</span>
    </div>

    <!-- Footer -->
    <div class="doc-footer">
      <p>Period: <strong>{{ periodLabel }}</strong> &nbsp;·&nbsp; Generated: <strong>{{ generatedAt }}</strong></p>
      <p class="footer-note">This report is auto-generated by KSMS. For queries, contact the administrator.</p>
    </div>
  </div>
</template>

<script>
const P = ['#6366f1','#10b981','#f59e0b','#ef4444','#3b82f6','#8b5cf6','#14b8a6','#f97316']
const hash = s => { let h=0; for (const c of s) h=(h*31+c.charCodeAt(0))&0xffffffff; return Math.abs(h) }

export default {
  name: 'ReportPayrollBreakdown',
  props: { rows: Array, periodLabel: String, generatedAt: String },
  computed: {
    grandTotal() {
      return parseFloat(this.rows.reduce((s, r) => s + r.totalPay, 0).toFixed(2))
    },
  },
  methods: {
    initials(n) { return n.split(' ').slice(0,2).map(w=>w[0]).join('').toUpperCase() },
    avatarColor(n) { return P[hash(n) % P.length] },
    fmtRM(v) { return 'RM ' + Number(v).toLocaleString('en-MY', { minimumFractionDigits: 2, maximumFractionDigits: 2 }) },
  },
}
</script>

<style scoped>
.section-header { display: flex; align-items: center; gap: 10px; margin-bottom: 14px; }
.section-accent { display: inline-block; width: 4px; height: 18px; border-radius: 2px; flex-shrink: 0; }
.section-title  { font-size: 14px; font-weight: 700; color: #0f172a; }

.breakdown-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(270px, 1fr));
  gap: 14px; margin-bottom: 20px;
}

/* Card */
.bc {
  border: 1.5px solid #e2e8f0; border-radius: 12px; padding: 16px;
  background: #fff; display: flex; flex-direction: column; gap: 12px;
}

/* Top */
.bc-top { display: flex; align-items: center; gap: 10px; }
.bc-avatar {
  width: 38px; height: 38px; border-radius: 50%; flex-shrink: 0;
  display: flex; align-items: center; justify-content: center;
  color: #fff; font-size: 11px; font-weight: 700;
}
.bc-info { flex: 1; min-width: 0; }
.bc-name { font-size: 13.5px; font-weight: 600; color: #0f172a; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
.bc-role { font-size: 11px; color: #94a3b8; text-transform: capitalize; margin-top: 1px; }
.bc-pill { font-size: 10.5px; font-weight: 600; padding: 2px 9px; border-radius: 20px; flex-shrink: 0; white-space: nowrap; }
.bc-pill.created { background: #eef2ff; color: #6366f1; }
.bc-pill.pending { background: #f1f5f9; color: #94a3b8; }

/* Stats strip */
.bc-stats { display: flex; border: 1.5px solid #f1f5f9; border-radius: 8px; overflow: hidden; }
.bc-stat {
  flex: 1; padding: 8px 4px; text-align: center;
  background: #f8fafc; border-right: 1px solid #f1f5f9;
}
.bc-stat:last-child { border-right: none; }
.bsv  { font-size: 14px; font-weight: 700; color: #0f172a; line-height: 1; }
.bsv.green { color: #16a34a; }
.bsv.amber { color: #d97706; }
.bsv.red   { color: #dc2626; }
.bsl  { font-size: 9.5px; color: #94a3b8; margin-top: 3px; text-transform: uppercase; letter-spacing: .04em; font-weight: 600; }

/* Pay breakdown */
.bc-pay {
  background: #f8fafc; border-radius: 8px;
  border: 1.5px solid #f1f5f9; padding: 12px 14px;
  display: flex; flex-direction: column; gap: 7px;
}
.pay-row { display: flex; align-items: baseline; justify-content: space-between; gap: 8px; }
.pay-lbl { font-size: 12px; color: #64748b; }
.pay-hint { font-size: 10.5px; color: #94a3b8; }
.pay-val  { font-family: 'DM Mono', monospace; font-size: 12.5px; color: #334155; }
.pay-divider { height: 1px; background: #e2e8f0; margin: 2px 0; }
.total-row  { margin-top: 1px; }
.total-lbl  { font-size: 12.5px; font-weight: 700; color: #0f172a; }
.total-val  { font-size: 14px; font-weight: 700; color: #6366f1; }

/* Receipt */
.bc-receipt {
  display: flex; align-items: center; gap: 6px;
  font-size: 11.5px; font-weight: 500; padding: 7px 10px;
  border-radius: 8px;
}
.bc-receipt.yes { background: #f0fdf4; color: #16a34a; }
.bc-receipt.no  { background: #fef2f2; color: #dc2626; }

/* Grand total banner */
.grand-total {
  display: flex; align-items: center; justify-content: space-between;
  background: linear-gradient(135deg, #6366f1 0%, #4f46e5 100%);
  border-radius: 12px; padding: 16px 22px;
  margin-bottom: 20px;
}
.gt-label { font-size: 13px; font-weight: 600; color: rgba(255,255,255,.85); }
.gt-value { font-family: 'DM Mono', monospace; font-size: 20px; font-weight: 700; color: #fff; }

/* Footer */
.doc-footer {
  border-top: 1px solid #f1f5f9; padding-top: 16px;
  text-align: center; font-size: 12px; color: #94a3b8;
  display: flex; flex-direction: column; gap: 4px;
}
.doc-footer strong { color: #475569; }
.footer-note { font-size: 11px; }

@media print {
  .breakdown-grid { grid-template-columns: repeat(2, 1fr); gap: 10px; }
  .bc { padding: 10px 12px; gap: 8px; }
  .bc-name { font-size: 9pt; }
  .bsv { font-size: 10pt; }
  .bsl { font-size: 7pt; }
  .pay-lbl, .pay-val { font-size: 8pt; }
  .total-val { font-size: 10pt; }
  .grand-total { padding: 10px 16px; border-radius: 8px; }
  .gt-label { font-size: 9pt; }
  .gt-value { font-size: 14pt; }
  .doc-footer { font-size: 8pt; }
}
</style>