<template>
  <transition name="modal-fade">
    <div v-if="show" class="overlay" @click.self="$emit('close')">
      <div class="modal-box">

        <!-- Header -->
        <div class="modal-header">
          <div class="header-left">
            <span class="uc-tag">UC005</span>
            <h2 class="modal-title">Generate Payroll</h2>
          </div>
          <button class="close-btn" @click="$emit('close')">
            <svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
              <line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/>
            </svg>
          </button>
        </div>

        <div class="modal-body" v-if="staff">

          <!-- Staff Info -->
          <div class="staff-header">
            <div class="avatar" :style="`background:${staff.avatarColor}`">{{ staff.initials }}</div>
            <div>
              <p class="staff-name">{{ staff.name }}</p>
              <p class="staff-meta">{{ staff.department }} &nbsp;·&nbsp; ID #{{ staff.userID }}</p>
            </div>
            <div class="period-tag">{{ periodLabel }}</div>
          </div>

          <!-- Breakdown -->
          <section class="section">
            <p class="section-label">Attendance Breakdown</p>
            <div class="breakdown-grid">
              <div class="breakdown-card">
                <span class="bval green">{{ staff.attendance.completed }}</span>
                <span class="blbl">Completed</span>
              </div>
              <div class="breakdown-card">
                <span class="bval amber">{{ staff.attendance.late }}</span>
                <span class="blbl">Late</span>
              </div>
              <div class="breakdown-card">
                <span class="bval red">{{ staff.attendance.missed }}</span>
                <span class="blbl">Missed</span>
              </div>
              <div class="breakdown-card highlight">
                <span class="bval blue">{{ staff.hoursWorked }}h</span>
                <span class="blbl">Hours Logged</span>
              </div>
            </div>
          </section>

          <!-- Recent Logs Preview -->
          <section class="section">
            <p class="section-label">Recent Attendance Logs</p>
            <div class="log-list">
              <div v-for="log in staff.recentLogs" :key="log.id" class="log-row">
                <span class="log-date">{{ log.date }}</span>
                <div class="log-times">
                  <span>{{ log.checkIn }}</span>
                  <svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="#94a3b8" stroke-width="2.5">
                    <line x1="5" y1="12" x2="19" y2="12"/><polyline points="12 5 19 12 12 19"/>
                  </svg>
                  <span>{{ log.checkOut }}</span>
                </div>
                <span class="log-hrs">{{ log.hours }}h</span>
                <span class="log-status" :class="log.status.toLowerCase()">{{ log.status }}</span>
              </div>
            </div>
          </section>

          <!-- Notes -->
          <section class="section">
            <p class="section-label">Notes <span class="optional">(optional)</span></p>
            <textarea
              v-model="localNotes"
              class="notes-input"
              placeholder="Add any payroll notes…"
              rows="3"
            />
          </section>

          <!-- Confirm Summary -->
          <div class="confirm-box">
            <div class="confirm-row">
              <span class="clabel">Total Hours Worked</span>
              <span class="cval">{{ staff.hoursWorked }} hours</span>
            </div>
            <div class="confirm-row">
              <span class="clabel">Pay Period</span>
              <span class="cval">{{ periodLabel }}</span>
            </div>
            <div class="confirm-row">
              <span class="clabel">Generated By</span>
              <span class="cval">Admin (ID #1)</span>
            </div>
          </div>
        </div>

        <!-- Footer -->
        <div class="modal-footer">
          <button class="btn-cancel" @click="$emit('close')">Cancel</button>
          <button class="btn-confirm" @click="handleConfirm" :disabled="isProcessing">
            <span v-if="isProcessing" class="spinner" />
            {{ isProcessing ? 'Generating…' : 'Confirm & Generate' }}
          </button>
        </div>

      </div>
    </div>
  </transition>
</template>

<script>
export default {
  name: 'GeneratePayrollModal',
  emits: ['close', 'confirm'],
  props: {
    show:        { type: Boolean, required: true },
    staff:       { type: Object,  default: null },
    periodLabel: { type: String,  default: '' },
    isProcessing:{ type: Boolean, default: false },
  },
  data() { return { localNotes: '' } },
  watch: {
    show(val) { if (!val) this.localNotes = '' },
  },
  methods: {
    handleConfirm() {
      this.$emit('confirm', { notes: this.localNotes })
    },
  },
}
</script>

<style scoped>
.overlay {
  position: fixed; inset: 0;
  background: rgba(15,23,42,.45);
  backdrop-filter: blur(3px);
  display: flex; align-items: center; justify-content: center;
  z-index: 1000; padding: 20px;
}
.modal-box {
  background: #fff;
  border-radius: 16px;
  width: 100%; max-width: 520px;
  max-height: 90vh; overflow-y: auto;
  box-shadow: 0 20px 60px rgba(0,0,0,.15);
}
.modal-header {
  display: flex; align-items: center; justify-content: space-between;
  padding: 20px 24px 16px;
  border-bottom: 1px solid #f1f5f9;
  position: sticky; top: 0; background: #fff; z-index: 1;
}
.header-left { display: flex; flex-direction: column; gap: 4px; }
.uc-tag {
  display: inline-block;
  font-size: 10.5px; font-weight: 600; letter-spacing: .08em;
  color: #6366f1; background: #eef2ff;
  padding: 2px 8px; border-radius: 4px;
  text-transform: uppercase; width: fit-content;
}
.modal-title { font-size: 16px; font-weight: 600; color: #0f172a; }
.close-btn {
  width: 30px; height: 30px; border: none;
  background: #f8fafc; border-radius: 7px;
  display: flex; align-items: center; justify-content: center;
  cursor: pointer; color: #64748b; transition: background .15s;
}
.close-btn:hover { background: #f1f5f9; }

.modal-body { padding: 22px 24px; }

.staff-header {
  display: flex; align-items: center; gap: 13px;
  padding-bottom: 18px; border-bottom: 1px solid #f8fafc; margin-bottom: 20px;
}
.avatar {
  width: 42px; height: 42px; border-radius: 10px;
  display: flex; align-items: center; justify-content: center;
  font-size: 14px; font-weight: 600; color: #fff; flex-shrink: 0;
}
.staff-name { font-size: 15px; font-weight: 600; color: #0f172a; margin-bottom: 3px; }
.staff-meta { font-size: 12.5px; color: #64748b; }
.period-tag {
  margin-left: auto;
  padding: 4px 12px;
  background: #f1f5f9; border-radius: 6px;
  font-size: 12.5px; font-weight: 500; color: #475569;
  white-space: nowrap;
}

.section { margin-bottom: 20px; }
.section-label {
  font-size: 11px; font-weight: 600; color: #94a3b8;
  text-transform: uppercase; letter-spacing: .07em; margin-bottom: 11px;
}
.optional { font-weight: 400; color: #cbd5e1; text-transform: none; letter-spacing: 0; }

.breakdown-grid {
  display: grid; grid-template-columns: repeat(4,1fr); gap: 9px;
}
.breakdown-card {
  background: #f8fafc; border-radius: 10px;
  padding: 13px 8px; text-align: center;
}
.breakdown-card.highlight { background: #eff6ff; }
.bval { display: block; font-size: 22px; font-weight: 700; margin-bottom: 3px; }
.bval.green { color: #16a34a; }
.bval.amber { color: #d97706; }
.bval.red   { color: #dc2626; }
.bval.blue  { color: #2563eb; }
.blbl { font-size: 11px; color: #94a3b8; }

.log-list { display: flex; flex-direction: column; gap: 5px; }
.log-row {
  display: flex; align-items: center; gap: 11px;
  padding: 9px 12px; background: #f8fafc; border-radius: 8px;
  font-size: 12.5px;
}
.log-date { width: 46px; font-weight: 500; color: #475569; flex-shrink: 0; }
.log-times {
  display: flex; align-items: center; gap: 5px;
  flex: 1; color: #64748b;
  font-family: 'DM Mono', monospace; font-size: 12px;
}
.log-hrs { font-weight: 600; color: #1e293b; min-width: 28px; }
.log-status {
  padding: 2px 8px; border-radius: 5px;
  font-size: 11px; font-weight: 600;
  text-transform: uppercase; letter-spacing: .03em;
}
.log-status.completed { background: #f0fdf4; color: #16a34a; }
.log-status.late      { background: #fffbeb; color: #b45309; }
.log-status.missed    { background: #fef2f2; color: #dc2626; }

.notes-input {
  width: 100%; padding: 10px 13px;
  border: 1px solid #e2e8f0; border-radius: 9px;
  font-family: 'DM Sans', sans-serif; font-size: 13.5px; color: #1e293b;
  resize: vertical; outline: none; transition: border-color .15s;
}
.notes-input:focus { border-color: #6366f1; }

.confirm-box {
  background: #f8fafc; border-radius: 10px;
  padding: 14px 16px; display: flex; flex-direction: column; gap: 9px;
}
.confirm-row { display: flex; justify-content: space-between; align-items: center; }
.clabel { font-size: 13px; color: #64748b; }
.cval   { font-size: 13.5px; font-weight: 600; color: #1e293b; }

.modal-footer {
  display: flex; gap: 10px; justify-content: flex-end;
  padding: 16px 24px 20px;
  border-top: 1px solid #f1f5f9;
}
.btn-cancel {
  padding: 9px 20px; border: 1px solid #e2e8f0; border-radius: 8px;
  background: #fff; font-family: 'DM Sans', sans-serif; font-size: 14px;
  color: #64748b; cursor: pointer; transition: background .15s;
}
.btn-cancel:hover { background: #f8fafc; }
.btn-confirm {
  padding: 9px 22px; border: none; border-radius: 8px;
  background: #0f172a; color: #fff;
  font-family: 'DM Sans', sans-serif; font-size: 14px; font-weight: 500;
  cursor: pointer; display: flex; align-items: center; gap: 8px;
  transition: background .15s, opacity .15s;
}
.btn-confirm:hover:not(:disabled) { background: #1e293b; }
.btn-confirm:disabled { opacity: .6; cursor: not-allowed; }
.spinner {
  width: 14px; height: 14px;
  border: 2px solid rgba(255,255,255,.3);
  border-top-color: #fff;
  border-radius: 50%;
  animation: spin .7s linear infinite;
}
@keyframes spin { to { transform: rotate(360deg); } }

.modal-fade-enter-active, .modal-fade-leave-active { transition: all .2s ease; }
.modal-fade-enter-from, .modal-fade-leave-to { opacity: 0; }
.modal-fade-enter-from .modal-box,
.modal-fade-leave-to   .modal-box { transform: translateY(12px) scale(.98); }
</style>